Repository WordPress/performance, pull requests merged in 2021-12, with the labels that each got.

#30 Add settings screen to toggle modules
  admin/load.php
  docs/Writing-a-module.md
  load.php
  phpcs.xml.dist
  tests/admin/load-tests.php
  tests/bootstrap.php
  tests/testdata/demo-modules/demo-module-1/load.php
  tests/testdata/demo-modules/demo-module-2/load.php
  tests/testdata/demo-modules/demo-module-3/load.php
Labels: [Type] Feature, Infrastructure

#32 Add WebP for uploads module
  modules/webp-uploads/load.php
  tests/modules/webp-uploads/webp-uploads-test.php
  tests/testdata/modules/webp-uploads/class-wp-image-doesnt-support-webp.php
  tests/testdata/modules/webp-uploads/class-wp-image-supports-webp.php
Labels: [Type] Feature, [Focus] Images

#47 Add contribution documentation
  CONTRIBUTING.md
  docs/Getting-started.md
  docs/README.md
Labels: [Type] Documentation

#51 Add changelog generator script
  .eslintrc.js
  .gitignore
  bin/plugin/cli.js
  bin/plugin/commands/changelog.js
  bin/plugin/config.js
  bin/plugin/lib/logger.js
  bin/plugin/lib/milestone.js
  package-lock.json
  package.json
Labels: [Type] Documentation, Infrastructure

#55 Add Code Of Conduct and security documentations
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: [Type] Enhancement, Infrastructure, no milestone

#60 Ensure that module header fields can be translated
  .gitignore
  admin/load.php
  bin/plugin/cli.js
  bin/plugin/commands/changelog.js
  bin/plugin/commands/translations.js
  bin/plugin/config.js
  package.json
Labels: [Type] Bug, Infrastructure

#71 Add action to lint JS files using `lint-js` script
  .github/workflows/js-lint.yml
Labels: [Type] Enhancement, Infrastructure, no milestone

#58 Update module directories to be within their focus directory
  admin/load.php
  bin/plugin/commands/translations.js
  docs/Writing-a-module.md
  modules/images/webp-uploads/load.php
  tests/admin/load-tests.php
  tests/bootstrap.php
  tests/modules/images/webp-uploads/webp-uploads-test.php
  tests/testdata/demo-modules/images/demo-module-3/load.php
  tests/testdata/demo-modules/javascript/demo-module-1/load.php
  tests/testdata/demo-modules/something/demo-module-2/load.php
  tests/testdata/modules/images/webp-uploads/class-wp-image-doesnt-support-webp.php
  tests/testdata/modules/images/webp-uploads/class-wp-image-supports-webp.php
Labels: [Type] Enhancement, [Focus] Images
