Repository WordPress/performance, pull requests merged in 2022-01, with the labels that each got.

#56 Add/23 codeowners file
  .editorconfig
  .github/CODEOWNERS
Labels: [Type] Enhancement, Infrastructure

#72 Add `readme.txt` and related update script
  bin/plugin/cli.js
  bin/plugin/commands/changelog.js
  bin/plugin/commands/common.js
  bin/plugin/commands/readme.js
  bin/plugin/commands/translations.js
  load.php
  package.json
  readme.txt
Labels: [Type] Documentation, Infrastructure

#85 GitHub Action to validate flags and milestones.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-validation.yml
Labels: [Type] Feature, Infrastructure, no milestone

#87 Allow programmatic control of active modules via filter
  admin/load.php
  load.php
  tests/admin/load-tests.php
Labels: [Type] Enhancement, Infrastructure

#104 Add an additional code owner for the image focus
  .github/CODEOWNERS
Labels: [Type] Enhancement, Infrastructure, no milestone

#112 Update JS focus code owner per recent change
  .github/CODEOWNERS
Labels: [Type] Enhancement, [Focus] JavaScript, no milestone

#110 Update load.php
  admin/load.php
  tests/admin/load-tests.php
Labels: [Type] Enhancement, Infrastructure

#89 GitHub action for automated plugin deployment to wordpress.org
  .distignore
  .github/workflows/deploy-dotorg.yml
Labels: [Type] Feature, Infrastructure

#54 Add module to alert about excessive JS and CSS assets
  modules/site-health/audit-enqueued-assets/helper.php
  modules/site-health/audit-enqueued-assets/load.php
  tests/modules/site-health/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/modules/site-health/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-audit-assets-transients-set.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-site-health-mock-responses.php
Labels: [Type] Feature, [Focus] Site Health

#88 Issue templates for bug reports and feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: [Type] Feature, Infrastructure, no milestone

#108 Rename `object-caching` to `object-cache`
  .github/CODEOWNERS
  admin/load.php
  tests/admin/load-tests.php
Labels: [Type] Enhancement, Infrastructure
