Repository WordPress/performance, pull requests merged in 2022-08, with the labels that each got.

#460 Fix PHPUnit versions in composer.json
  composer.json
  composer.lock
Labels: [Type] Enhancement, Infrastructure, no milestone

#444 Add the original image's extension to the WebP file name to ensure it is unique
  modules/images/webp-uploads/helper.php
  modules/images/webp-uploads/load.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/testdata/modules/images/image.jpeg
  tests/testdata/modules/images/image.jpg
Labels: [Type] Bug, [Focus] Images, [Module] WebP Uploads

#457 Fix REST API support for plain permalinks.
  modules/images/webp-uploads/fallback.js
Labels: [Type] Bug, [Focus] Images, [Module] WebP Support

#463 Use `PERFLAB_MODULES_SCREEN` constant
  admin/load.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#443 Enhance JS replacement mechanism for WebP to JPEG to more reliably replace full file name
  modules/images/webp-uploads/fallback.js
  modules/images/webp-uploads/rest-api.php
  tests/modules/images/webp-uploads/rest-api-tests.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Uploads

#458 Remove plugin option for Multisite during uninstall
  uninstall.php
Labels: [Type] Bug, Infrastructure

#420 Introduce `webp_uploads_get_content_image_mimes()` to get content image MIME replacement rules
  modules/images/webp-uploads/helper.php
  modules/images/webp-uploads/load.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Uploads

#472 Fix incorrect usage of badge colors in all Site Health checks
  modules/object-cache/persistent-object-cache-health-check/load.php
  modules/site-health/audit-autoloaded-options/load.php
  modules/site-health/audit-enqueued-assets/load.php
  modules/site-health/audit-full-page-cache/load.php
  tests/modules/site-health/audit-full-page-cache/audit-full-page-cache-test.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-site-health-mock-responses.php
Labels: [Type] Bug, [Focus] Site Health

#423 Rename Site Health check modules for language and consistency
  .github/CODEOWNERS
  modules/site-health/audit-autoloaded-options/load.php
  modules/site-health/audit-enqueued-assets/load.php
  modules/site-health/audit-full-page-cache/load.php
  modules/site-health/webp-support/load.php
Labels: [Type] Enhancement, Infrastructure

#473 Prepare 1.4.0 release
  load.php
  module-i18n.php
  modules/images/webp-uploads/helper.php
  readme.txt
  uninstall.php
Labels: [Type] Documentation, Infrastructure, no milestone

#474 Merge 1.4.0 back into `trunk`
  .github/CODEOWNERS
  load.php
  module-i18n.php
  modules/images/webp-uploads/helper.php
  modules/object-cache/persistent-object-cache-health-check/load.php
  modules/site-health/audit-autoloaded-options/load.php
  modules/site-health/audit-enqueued-assets/load.php
  modules/site-health/audit-full-page-cache/load.php
  modules/site-health/webp-support/load.php
  readme.txt
  tests/modules/site-health/audit-full-page-cache/audit-full-page-cache-test.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-site-health-mock-responses.php
  uninstall.php
Labels: [Type] Documentation, Infrastructure, no milestone

#442 Update language throughout the plugin from Group to Team
  README.md
  composer.json
  docs/Proposing-a-new-module.md
  load.php
  readme.txt
Labels: [Type] Enhancement, Infrastructure, no milestone

#502 Remove return type from apply_filters
  modules/images/webp-uploads/helper.php
Labels: [Type] Documentation, [Focus] Images, [Module] WebP Uploads, no milestone

#504 Run GitHub workflows also for feature branches
  .github/workflows/js-lint.yml
  .github/workflows/php-lint.yml
  .github/workflows/php-test.yml
  .github/workflows/pr-validation.yml
Labels: [Type] Enhancement, Infrastructure, no milestone, Needs Review

#497 Background job taxonomy for queuing jobs
  modules/images/regenerate-existing-images/load.php
  tests/modules/images/regenerate-existing-images/load-tests.php
Labels: [Focus] Images, no milestone, [Type] Epic, [Module] Regenerate Existing Images

#500 Correct docblock for `wp_get_attachment_file_path()`
  modules/images/dominant-color/load.php
Labels: [Type] Enhancement, [Focus] Images, no milestone, [Module] Dominant Color

#437 Fix unexpected input `Warning` message during release build/test process
  .github/workflows/js-lint.yml
  .github/workflows/php-test.yml
Labels: [Type] Bug, Infrastructure, no milestone, Needs Review
