Repository WordPress/performance, pull requests merged in 2022-04, with the labels that each got.

#276 Prepare release for `1.0.0-rc.1`
  load.php
  module-i18n.php
  modules/images/webp-uploads/load.php
  readme.txt
  tests/testdata/modules/images/webp-uploads/class-wp-image-edit.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#279 Merge `release/1.0.0-rc.1`
  load.php
  module-i18n.php
  modules/images/webp-uploads/load.php
  readme.txt
  tests/modules/images/webp-uploads/webp-uploads-test.php
  tests/testdata/modules/images/webp-uploads/class-wp-image-edit.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#240 Define the plugin's version support and backward compatibility policy
  docs/README.md
  docs/Version-support-policy.md
Labels: [Type] Documentation, Infrastructure

#272 Update Site Health reports copy for more clarity and consistency
  modules/object-cache/persistent-object-cache-health-check/load.php
  modules/site-health/audit-autoloaded-options/load.php
  modules/site-health/webp-support/load.php
  tests/modules/site-health/audit-autoloaded-options/audit-autoloaded-options-test.php
Labels: [Type] Enhancement, [Focus] Site Health, Needs Review

#291 Update Github-workflow.md
  docs/Github-workflow.md
Labels: [Type] Documentation, Infrastructure, no milestone

#284 Fix wrong version from the previous release
  load.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#235 Update secondary image mime types when editing original image
  modules/images/webp-uploads/load.php
  phpcs.xml.dist
  tests/modules/images/webp-uploads/webp-uploads-test.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Feature, [Focus] Images, Needs Review

#298 Break apart single massive WebP Uploads file into multiple more manageable files
  modules/images/webp-uploads/helper.php
  modules/images/webp-uploads/image-edit.php
  modules/images/webp-uploads/load.php
  modules/images/webp-uploads/rest-api.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/image-edit-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/modules/images/webp-uploads/rest-api-tests.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Uploads

#305 Merge 1.0.0 release branch back into trunk
  load.php
  modules/images/webp-uploads/helper.php
  modules/images/webp-uploads/image-edit.php
  modules/images/webp-uploads/load.php
  readme.txt
  tests/testdata/modules/images/webp-uploads/class-wp-image-edit.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#308 Update CODEOWNERS
  .github/CODEOWNERS
Labels: [Type] Documentation, Infrastructure, no milestone, Needs Review

#313 Update Site Health Autoloaded options documentation link
  modules/site-health/audit-autoloaded-options/load.php
Labels: [Type] Enhancement, [Focus] Site Health
