Repository WordPress/performance, pull requests merged in 2022-12, with the labels that each got.

#591 Use PHP 7.4 for unit tests
  .github/workflows/js-lint.yml
  .github/workflows/php-test.yml
  .wp-env.json
Labels: [Type] Bug, Infrastructure, no milestone

#547 Implement new experimental SQLite integration module
  admin/load.php
  load.php
  modules/database/sqlite/activate.php
  modules/database/sqlite/can-load.php
  modules/database/sqlite/constants.php
  modules/database/sqlite/db.copy.php
  modules/database/sqlite/deactivate.php
  modules/database/sqlite/load.php
  modules/database/sqlite/site-health.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-alter-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-create-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-object-array.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-driver.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-engine.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-user-defined-functions.php
  modules/database/sqlite/wp-includes/sqlite/db.php
  modules/database/sqlite/wp-includes/sqlite/install-functions.php
  tests/load-tests.php
  tests/testdata/demo-modules/something/demo-module-2/activate.php
  tests/testdata/demo-modules/something/demo-module-2/deactivate.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: no milestone, Needs Review, [Type] Module Proposal, [Focus] Database

#593 Remove benchmark command
  bin/plugin/cli.js
  bin/plugin/commands/benchmark.js
  package-lock.json
  package.json
Labels: [Type] Enhancement, [Focus] Measurement, no milestone

#592 Update npm dependencies to their latest versions to fix vulnerability
  package-lock.json
  package.json
Labels: [Type] Enhancement, Infrastructure, no milestone

#595 Make WP filesystem setup more robust to prevent potential errors
  modules/database/sqlite/activate.php
  modules/database/sqlite/deactivate.php
Labels: [Type] Bug, [Focus] Database

#596 Actually update Composer dependencies instead of calling composer update
  .github/workflows/php-test.yml
  composer.lock
Labels: [Type] Bug, Infrastructure, no milestone

#598 Use `assertStringContainsString` instead of `assertContains` to fix PHPUnit deprecation warnings
  tests/admin/load-tests.php
  tests/load-tests.php
  tests/modules/images/webp-uploads/load-tests.php
Labels: [Type] Bug, Infrastructure, no milestone

#600 Fix SQLite notices related to undefined properties
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-engine.php
Labels: [Type] Bug, [Focus] Database

#603 Fix incorrect handling of `admin_email` and actual admin user's email when original `admin_email` user was deleted
  modules/database/sqlite/activate.php
Labels: [Type] Bug, [Focus] Database, [Module] SQLite

#607 Prepare 1.8.0 release
  load.php
  module-i18n.php
  modules/database/sqlite/activate.php
  modules/database/sqlite/can-load.php
  modules/database/sqlite/constants.php
  modules/database/sqlite/deactivate.php
  modules/database/sqlite/load.php
  modules/database/sqlite/site-health.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-alter-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-create-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-object-array.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-driver.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-engine.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-user-defined-functions.php
  modules/database/sqlite/wp-includes/sqlite/db.php
  modules/database/sqlite/wp-includes/sqlite/install-functions.php
  modules/images/fetchpriority/load.php
  readme.txt
  server-timing/class-perflab-server-timing-metric.php
  server-timing/class-perflab-server-timing.php
  server-timing/defaults.php
  server-timing/load.php
  server-timing/object-cache.copy.php
  tests/testdata/demo-modules/something/demo-module-2/activate.php
  tests/testdata/demo-modules/something/demo-module-2/deactivate.php
Labels: [Type] Documentation, Infrastructure, no milestone

#608 Merge 1.8.0 release back into `trunk`
  load.php
  module-i18n.php
  modules/database/sqlite/activate.php
  modules/database/sqlite/can-load.php
  modules/database/sqlite/constants.php
  modules/database/sqlite/deactivate.php
  modules/database/sqlite/load.php
  modules/database/sqlite/site-health.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-alter-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-create-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-object-array.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-driver.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-engine.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-user-defined-functions.php
  modules/database/sqlite/wp-includes/sqlite/db.php
  modules/database/sqlite/wp-includes/sqlite/install-functions.php
  modules/images/fetchpriority/load.php
  readme.txt
  server-timing/class-perflab-server-timing-metric.php
  server-timing/class-perflab-server-timing.php
  server-timing/defaults.php
  server-timing/load.php
  server-timing/object-cache.copy.php
  tests/testdata/demo-modules/something/demo-module-2/activate.php
  tests/testdata/demo-modules/something/demo-module-2/deactivate.php
Labels: [Type] Documentation, Infrastructure, no milestone
