Repository WordPress/performance, pull requests merged in 2022-09, with the labels that each got.

#511 Updated npm dependencies to their latest versions to fix vulnerability issues.
  package-lock.json
  package.json
Labels: [Type] Enhancement, Infrastructure, no milestone

#521 Add return document for `perflab_get_modules_setting_default()`
  load.php
Labels: [Type] Bug, Infrastructure, no milestone

#353 Improve autoloaded options check by highlighting largest autoloaded options
  modules/site-health/audit-autoloaded-options/load.php
Labels: [Type] Enhancement, [Focus] Site Health, [Module] Audit Autoloaded Options

#508 Include section on branch name requirements to GitHub workflow documentation
  docs/Github-workflow.md
Labels: [Type] Documentation, Infrastructure, no milestone, Needs Review

#538 Prepare 1.5.0 release
  load.php
  modules/site-health/audit-autoloaded-options/load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#541 Merge 1.5.0 back into `trunk`
  load.php
  modules/site-health/audit-autoloaded-options/load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#542 Fix broken command for readme changelog
  bin/plugin/commands/changelog.js
  bin/plugin/lib/milestone.js
Labels: [Type] Bug, Infrastructure, no milestone

#543 Only load Site Health checks for persistent cache and full page cache when not available in core
  modules/object-cache/persistent-object-cache-health-check/can-load.php
  modules/site-health/audit-full-page-cache/can-load.php
Labels: [Type] Enhancement, [Focus] Site Health, [Module] Persistent Object Cache, [Module] Audit Full Page Cache

#546 Update `@wordpress/env` to latest version
  package-lock.json
  package.json
Labels: [Type] Enhancement, Infrastructure, no milestone
