Repository WordPress/performance, pull requests merged in 2022-11, with the labels that each got.

#569 Added the benchmark command
  bin/plugin/cli.js
  bin/plugin/commands/benchmark.js
  package-lock.json
  package.json
Labels: [Type] Enhancement, [Focus] Measurement, no milestone

#572 Load the WP_Image_Editor_Imagick class if it doesn't exist
  tests/admin/load-tests.php
  tests/modules/images/dominant-color/dominant-color-image-editor-gd-test.php
  tests/modules/images/dominant-color/dominant-color-image-editor-imageick-test.php
  tests/modules/images/dominant-color/dominant-color-test.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/image-edit-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/modules/images/webp-uploads/rest-api-tests.php
  tests/testdata/modules/images/webp-uploads/class-wp-image-doesnt-support-webp.php
Labels: [Type] Bug, [Focus] Images, no milestone

#566 Introduce database focus area, rename JavaScript focus area to JS & CSS, and phase out Site Health focus area
  .github/CODEOWNERS
  admin/load.php
  bin/plugin/commands/common.js
  default-enabled-modules.php
  load.php
  modules/database/audit-autoloaded-options/load.php
  modules/images/webp-support/load.php
  modules/js-and-css/audit-enqueued-assets/helper.php
  modules/js-and-css/audit-enqueued-assets/load.php
  modules/object-cache/audit-full-page-cache/can-load.php
  modules/object-cache/audit-full-page-cache/helper.php
  modules/object-cache/audit-full-page-cache/load.php
  tests/admin/load-tests.php
  tests/load-tests.php
  tests/modules/database/audit-autoloaded-options/audit-autoloaded-options-test.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/modules/object-cache/audit-full-page-cache/audit-full-page-cache-test.php
  tests/testdata/demo-modules/js-and-css/demo-module-1/can-load.php
  tests/testdata/demo-modules/js-and-css/demo-module-1/load.php
Labels: [Type] Enhancement, Infrastructure

#564 Focus area updates
  .github/CODEOWNERS
  README.md
  phpcs.xml.dist
Labels: [Type] Documentation, Infrastructure, no milestone

#570 Fix GitHub action deprecation warning during plugin deployment
  .github/workflows/deploy-dotorg.yml
  .github/workflows/php-lint.yml
  .github/workflows/php-test.yml
Labels: [Type] Bug, Infrastructure, no milestone

#581 Update the benchmark command to use the POST method for all requests to bypass cache.
  bin/plugin/commands/benchmark.js
Labels: [Type] Enhancement, [Focus] Measurement, no milestone

#580 Update FAQs in readme
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#582 Fix image focal point bug when dominant color is enabled by not overriding `style` attribute
  modules/images/dominant-color/load.php
  tests/modules/images/dominant-color/dominant-color-test.php
Labels: [Type] Bug, [Focus] Images, [Module] Dominant Color

#571 Change WP Image editor quality for mime types
  modules/images/webp-uploads/load.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/utils/TestCase/DominantColorTestCase.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Uploads, Needs Review

#578 Avoid potentially adding invalid attributes or duplicates for dominant color images
  modules/images/dominant-color/load.php
  tests/modules/images/dominant-color/dominant-color-test.php
Labels: [Type] Bug, [Focus] Images, Needs Review

#583 Prepare the 1.7.0 release
  load.php
  module-i18n.php
  modules/images/webp-uploads/load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#584 Merge 1.7.0 back into `trunk`
  load.php
  module-i18n.php
  modules/images/dominant-color/load.php
  modules/images/webp-uploads/load.php
  readme.txt
  tests/modules/images/dominant-color/dominant-color-test.php
Labels: [Type] Documentation, Infrastructure, no milestone

#528 Implement new experimental `fetchpriority` module
  .github/CODEOWNERS
  modules/images/fetchpriority/load.php
  tests/modules/images/fetchpriority/fetchpriority-tests.php
Labels: [Type] Feature, [Focus] Images, Needs Review, [Module] fetchpriority
