Repository WordPress/performance, pull requests merged in 2022-03, with the labels that each got.

#198 Add plugin author URI pointing to relevant make.wordpress.org blog
  load.php
Labels: [Type] Documentation, Infrastructure, no milestone, Needs Review

#200 Always recommend object cache on multisite
  modules/object-cache/persistent-object-cache-health-check/load.php
  tests/modules/object-cache/persistent-object-cache-health-check/health-check-test.php
Labels: [Type] Enhancement, [Focus] Object Cache

#201 Add missing release instructions reference to docs TOC.
  docs/Getting-started.md
  docs/README.md
  docs/Releasing-the-plugin.md
Labels: [Type] Documentation, Infrastructure, no milestone, Needs Review

#191 Enable all non-experimental modules on plugin activation
  admin/load.php
Labels: [Type] Enhancement, Infrastructure, Needs Review

#197 Add link to Settings screen to the plugin's entry in plugins list table
  admin/load.php
  load.php
  tests/admin/load-tests.php
Labels: [Type] Enhancement, Infrastructure

#202 Run all relevant GitHub workflows for release branches as well
  .github/workflows/js-lint.yml
  .github/workflows/php-lint.yml
  .github/workflows/php-test.yml
  .github/workflows/pr-validation.yml
Labels: [Type] Enhancement, Infrastructure, no milestone, Needs Review

#203 Fix typo to access to the correct image properties
  modules/images/webp-uploads/load.php
Labels: [Type] Bug, [Focus] Images, [Module] WebP Uploads

#205 Mark Site Health Audit Enqueued Assets module as experimental for now.
  modules/site-health/audit-enqueued-assets/load.php
Labels: [Type] Documentation, [Focus] Site Health, Needs Review, [Module] Audit Enqueued Assets

#136 Enhance detection of enqueued frontend assets
  modules/site-health/audit-enqueued-assets/helper.php
  modules/site-health/audit-enqueued-assets/load.php
  tests/modules/site-health/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/modules/site-health/audit-enqueued-assets/audit-enqueued-assets-test.php
Labels: [Type] Enhancement, [Focus] Site Health, Needs Review, [Module] Audit Enqueued Assets

#199 Added admin pointer
  admin/load.php
Labels: [Type] Feature, Infrastructure, Needs Review

#208 Prepare the 1.0.0-beta.1 release
  admin/load.php
  modules/images/webp-uploads/load.php
  modules/site-health/audit-enqueued-assets/helper.php
  modules/site-health/audit-enqueued-assets/load.php
  package-lock.json
  package.json
  readme.txt
  tests/modules/site-health/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/modules/site-health/audit-enqueued-assets/audit-enqueued-assets-test.php
Labels: [Type] Documentation, Infrastructure, no milestone

#210 Include prerelease stage for workflow
  .github/workflows/deploy-dotorg.yml
Labels: [Type] Bug, Infrastructure, no milestone

#211 Add checkout action
  .github/workflows/deploy-dotorg.yml
Labels: [Type] Enhancement, Infrastructure, no milestone

#212 Merge final release fixes back into trunk
  .github/workflows/deploy-dotorg.yml
Labels: [Type] Bug, Infrastructure, no milestone

#194 Create multiple mime types for the `full` size image.
  modules/images/webp-uploads/load.php
  tests/modules/images/webp-uploads/webp-uploads-test.php
Labels: [Type] Feature, [Focus] Images, [Module] WebP Uploads, Needs Review

#195 Replace `the_content` with the full size image in new mime types if available
  modules/images/webp-uploads/load.php
  tests/modules/images/webp-uploads/webp-uploads-test.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Uploads, Needs Review

#223 Use `.gitattributes` instead of `.distignore` to better support ZIP creation
  .distignore
  .gitattributes
Labels: [Type] Enhancement, Infrastructure

#225 Switch deploy workflow (released & prereleased → published)
  .github/workflows/deploy-dotorg.yml
Labels: [Type] Enhancement, Infrastructure, no milestone

#222 Replace unreliable activation hook with default value for enabled modules
  admin/load.php
  bin/plugin/cli.js
  bin/plugin/commands/common.js
  bin/plugin/commands/enabled-modules.js
  bin/plugin/commands/readme.js
  bin/plugin/commands/translations.js
  default-enabled-modules.php
  docs/Releasing-the-plugin.md
  load.php
  package.json
  tests/load-tests.php
Labels: [Type] Bug, Infrastructure, Needs Review

#221 Update release instructions to include proper branching strategy and protect release branches
  docs/Releasing-the-plugin.md
Labels: [Type] Documentation, Infrastructure, Needs Review

#207 Use `original` image to generate all subsizes
  modules/images/webp-uploads/load.php
  tests/modules/images/webp-uploads/webp-uploads-test.php
  tests/testdata/modules/images/paint.jpeg
Labels: [Type] Bug, [Focus] Images, [Module] WebP Uploads, Needs Review

#227 Allow developers to tweak which image formats to generate on upload
  composer.json
  modules/images/webp-uploads/load.php
  phpcs.xml.dist
  tests/modules/images/webp-uploads/webp-uploads-test.php
  tests/utils/Constraint/ImageHasSizeSource.php
  tests/utils/Constraint/ImageHasSource.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Uploads

#231 Add plugin banner and icon assets
  .gitattributes
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/icon.svg
Labels: [Type] Enhancement, Infrastructure

#230 Allow developers to select which image format to use for images in the content
  modules/images/webp-uploads/load.php
  tests/modules/images/webp-uploads/webp-uploads-test.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Support

#236 Update description for Audit Autoloaded Options module
  modules/site-health/audit-autoloaded-options/load.php
Labels: [Type] Documentation, [Focus] Site Health, no milestone

#245 Prepare release for 1.0.0-beta.2
  load.php
  module-i18n.php
  modules/images/webp-uploads/load.php
  package-lock.json
  package.json
  readme.txt
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#246 Update trunk with latest release changes
  .gitattributes
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/icon.svg
  load.php
  module-i18n.php
  modules/images/webp-uploads/load.php
  modules/site-health/audit-autoloaded-options/load.php
  package-lock.json
  package.json
  readme.txt
  tests/modules/images/webp-uploads/webp-uploads-test.php
  tests/modules/site-health/audit-autoloaded-options/audit-autoloaded-options-test.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#248 Ensure default modules are loaded regardless of setting registration
  load.php
  tests/load-tests.php
Labels: [Type] Bug, Infrastructure, Needs Review

#255 Merge 1.0.0-beta.3 branch back into trunk
  load.php
  package-lock.json
  package.json
  readme.txt
  tests/load-tests.php
Labels: [Type] Documentation, Infrastructure, no milestone

#250 Change expected order of items in the `webp_uploads_content_image_mimes` filter
  modules/images/webp-uploads/load.php
Labels: [Type] Enhancement, [Focus] Images, Needs Review, [Module] WebP Support

#254 Updated the package.json file to contain only required data
  docs/Releasing-the-plugin.md
  package-lock.json
  package.json
Labels: [Type] Enhancement, Infrastructure, no milestone

#265 Add the name property to the package.json file.
  package.json
Labels: [Type] Bug, Infrastructure, no milestone

#266 Merge package.json fix back to trunk
  package.json
Labels: [Type] Bug, Infrastructure, no milestone

#262 Replace images in frontend content without using an additional regular expression
  modules/images/webp-uploads/load.php
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Support

#256 Add GitHub workflow documentation
  docs/Github-workflow.md
  docs/README.md
Labels: [Type] Documentation, Infrastructure, no milestone

#261 Update Getting-started.md
  docs/Getting-started.md
Labels: [Type] Documentation, Infrastructure, no milestone

#270 Correct usernames for Infrastructure and remove Site Health owner
  .github/CODEOWNERS
Labels: [Type] Enhancement, Infrastructure, no milestone

#268 Fix typos in Getting-started.md
  docs/Getting-started.md
Labels: [Type] Documentation, Infrastructure, no milestone

#243 Select smaller image size from sources update
  modules/images/webp-uploads/load.php
  tests/modules/images/webp-uploads/webp-uploads-test.php
Labels: [Type] Enhancement, [Focus] Images
