Repository WordPress/performance, pull requests merged in 2023-10, with the labels that each got.

#851 Bump minimum required PHP version to 7.0 and minimum required WP version to 6.3
  .github/workflows/php-lint.yml
  CONTRIBUTING.md
  bin/plugin/commands/build-plugins.js
  composer.json
  composer.lock
  load.php
  modules/images/dominant-color-images/hooks.php
  modules/images/dominant-color-images/readme.txt
  modules/images/webp-uploads/hooks.php
  modules/images/webp-uploads/image-edit.php
  modules/images/webp-uploads/readme.txt
  phpcs.xml.dist
  plugin-tests/composer.json
  readme.txt
  server-timing/defaults.php
  tests/modules/images/webp-uploads/load-tests.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#854 Remove Fetchpriority module as the functionality is now available in WordPress core
  .github/CODEOWNERS
  load.php
  modules/images/fetchpriority/.wordpress-org/banner-1544x500.png
  modules/images/fetchpriority/.wordpress-org/banner-772x250.png
  modules/images/fetchpriority/.wordpress-org/icon-128x128.png
  modules/images/fetchpriority/.wordpress-org/icon-256x256.png
  modules/images/fetchpriority/.wordpress-org/icon.svg
  modules/images/fetchpriority/can-load.php
  modules/images/fetchpriority/hooks.php
  modules/images/fetchpriority/load.php
  modules/images/fetchpriority/readme.txt
  plugins.json
  tests/modules/images/fetchpriority/fetchpriority-tests.php
Labels: [Type] Enhancement, [Focus] Images, [Module] fetchpriority

#855 Bump WebP Uploads version
  modules/images/webp-uploads/readme.txt
  plugins.json
Labels: [Type] Enhancement, [Focus] Images, [Module] WebP Uploads, no milestone

#858 Publish 2.7.0
  default-enabled-modules.php
  load.php
  module-i18n.php
  modules/images/webp-uploads/hooks.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#859 Merge 2.7.0 release back into `trunk`
  default-enabled-modules.php
  load.php
  module-i18n.php
  modules/images/webp-uploads/hooks.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#862 Update `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: [Type] Documentation, Infrastructure, no milestone

#868 Updated Inline PHP Documentation
  admin/load.php
  modules/database/audit-autoloaded-options/helper.php
  modules/images/webp-uploads/helper.php
  modules/js-and-css/audit-enqueued-assets/hooks.php
Labels: [Type] Documentation, Infrastructure, no milestone

#866 Exclude `.wordpress-org` directory when deploying standalone plugins
  modules/images/dominant-color-images/.gitattributes
  modules/images/dominant-color-images/readme.txt
  modules/images/webp-uploads/.gitattributes
  modules/images/webp-uploads/readme.txt
  plugins.json
Labels: [Type] Bug, Infrastructure, no milestone
