Repository WordPress/performance, pull requests merged in 2023-05, with the labels that each got.

#719 Temporarily remove Dominant Color Images from standalone `plugins.json` definition
  plugins.json
Labels: [Type] Enhancement, Infrastructure, Creating standalone plugins

#710 Use dynamic version from `plugins.json` for manual workflow
  .github/workflows/deploy-standalone-plugins.yml
  bin/plugin/cli.js
  bin/plugin/commands/get-plugin-version.js
Labels: [Type] Enhancement, Infrastructure, Creating standalone plugins

#722 Prepare 2.3.0 release
  load.php
  modules/images/dominant-color-images/hooks.php
  modules/images/fetchpriority/hooks.php
  readme.txt
Labels: [Type] Documentation, Infrastructure

#724 Update @since inline doc
  admin/load.php
Labels: [Type] Documentation, Infrastructure, no milestone

#723 Merge 2.3.0 release back to `trunk`
  admin/load.php
  load.php
  modules/images/dominant-color-images/hooks.php
  modules/images/fetchpriority/hooks.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#725 Add missing 2.3.0 changelog entry
  readme.txt
Labels: [Type] Bug, Infrastructure, no milestone

#726 Merge #725 back to `trunk`
  readme.txt
Labels: [Type] Bug, Infrastructure, no milestone

#736 Make `Server-Timing` header output more robust
  server-timing/class-perflab-server-timing.php
Labels: [Type] Bug, Infrastructure
