Repository WordPress/performance, pull requests merged in 2023-08, with the labels that each got.

#784 Implement logic to measure specific hook execution time with Server-Timing controlled by a WP Admin screen
  admin/load.php
  admin/server-timing.php
  load.php
  server-timing/defaults.php
  server-timing/load.php
  tests/admin/load-tests.php
  tests/admin/server-timing-tests.php
  tests/bootstrap.php
  tests/server-timing/load-tests.php
Labels: [Type] Feature, Infrastructure, no milestone

#795 Allow disabling Server-Timing entirely using `PERFLAB_DISABLE_SERVER_TIMING` constant
  admin/server-timing.php
  load.php
  server-timing/defaults.php
  server-timing/load.php
  server-timing/object-cache.copy.php
Labels: [Type] Enhancement, Infrastructure, Needs Review

#800 Bump Node to v16
  .nvmrc
  bin/plugin/cli.js
  bin/plugin/commands/get-plugin-version.js
  bin/plugin/commands/test-plugins.js
  package-lock.json
  package.json
Labels: [Type] Enhancement, Infrastructure, no milestone

#796 Fix WebP handling when editing images based on WordPress 6.3 change
  modules/images/webp-uploads/image-edit.php
  modules/images/webp-uploads/readme.txt
  plugins.json
  tests/modules/images/fetchpriority/fetchpriority-tests.php
  tests/modules/images/webp-uploads/image-edit-tests.php
Labels: [Type] Bug, [Focus] Images, [Module] fetchpriority

#802 Fix typos in the plugin
  admin/load.php
  modules/js-and-css/audit-enqueued-assets/helper.php
  modules/js-and-css/audit-enqueued-assets/hooks.php
  readme.txt
Labels: [Type] Bug, Infrastructure, no milestone, Performance Lab Plugin

#803 Add Spell Check action
  .github/workflows/spell-check.yml
Labels: [Type] Enhancement, Infrastructure, no milestone

#801 Add output buffering checkbox to Server-Timing screen
  admin/server-timing.php
  server-timing/class-perflab-server-timing.php
  server-timing/load.php
  tests/admin/server-timing-tests.php
  tests/server-timing/load-tests.php
  tests/server-timing/perflab-server-timing-tests.php
Labels: [Type] Feature, Infrastructure

#807 Prepare 2.6.0 release
  admin/server-timing.php
  load.php
  modules/images/dominant-color-images/helper.php
  modules/images/webp-uploads/image-edit.php
  readme.txt
  server-timing/defaults.php
  server-timing/load.php
Labels: [Type] Documentation, Infrastructure, no milestone

#808 Merge 2.6.0 release back into `trunk`
  admin/server-timing.php
  load.php
  modules/images/dominant-color-images/helper.php
  modules/images/webp-uploads/image-edit.php
  readme.txt
  server-timing/class-perflab-server-timing.php
  server-timing/defaults.php
  server-timing/load.php
  tests/admin/server-timing-tests.php
  tests/server-timing/load-tests.php
  tests/server-timing/perflab-server-timing-tests.php
Labels: [Type] Documentation, Infrastructure, no milestone

#809 Bump WPCS to v3.0.0
  admin/load.php
  admin/server-timing.php
  composer.json
  composer.lock
  load.php
  modules/images/fetchpriority/can-load.php
  modules/images/fetchpriority/hooks.php
  modules/images/webp-uploads/can-load.php
  modules/images/webp-uploads/load.php
  modules/images/webp-uploads/rest-api.php
  phpcs.xml.dist
  server-timing/class-perflab-server-timing.php
  server-timing/defaults.php
  server-timing/load.php
Labels: [Type] Enhancement, Infrastructure, no milestone
