Repository WordPress/performance, pull requests merged in 2023-07, with the labels that each got.

#769 Check for fetchpriority feature being available in WordPress core before loading the module
  modules/images/fetchpriority/can-load.php
  modules/images/fetchpriority/hooks.php
  modules/images/fetchpriority/readme.txt
  plugins.json
Labels: [Type] Enhancement, [Focus] Images, [Module] fetchpriority

#764 Remove SQLite module
  admin/load.php
  load.php
  modules/database/sqlite/activate.php
  modules/database/sqlite/admin.php
  modules/database/sqlite/can-load.php
  modules/database/sqlite/constants.php
  modules/database/sqlite/db.copy.php
  modules/database/sqlite/deactivate.php
  modules/database/sqlite/load.php
  modules/database/sqlite/site-health.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-alter-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-create-query.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-object-array.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-driver.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-engine.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-user-defined-functions.php
  modules/database/sqlite/wp-includes/sqlite/db.php
  modules/database/sqlite/wp-includes/sqlite/install-functions.php
  phpcs.xml.dist
  readme.txt
Labels: [Type] Enhancement, [Focus] Database Optimization, [Module] SQLite

#772 Bump tested up to version to 6.3
  modules/images/dominant-color-images/readme.txt
  modules/images/webp-uploads/readme.txt
  plugins.json
  readme.txt
Labels: [Type] Enhancement, Infrastructure

#778 Fix whitespace not matching in `since` command.
  bin/plugin/commands/since.js
Labels: [Type] Bug, Infrastructure, no milestone

#779 2.5.0 Release Prep
  load.php
  module-i18n.php
  modules/images/fetchpriority/can-load.php
  readme.txt
Labels: Infrastructure, no milestone, [Type] Task

#781 Merge Release/2.5.0 back to trunk
  bin/plugin/commands/since.js
  load.php
  module-i18n.php
  modules/images/fetchpriority/can-load.php
  readme.txt
Labels: Infrastructure, no milestone, [Type] Task

#780 Configure `DRY_RUN` to Github Action
  .github/workflows/deploy-standalone-plugins.yml
Labels: [Type] Enhancement, Infrastructure, no milestone

#788 Fix errors detected by Plugin Checker
  modules/.gitkeep
  phpcs.xml.dist
  server-timing/class-perflab-server-timing-metric.php
  server-timing/class-perflab-server-timing.php
  server-timing/defaults.php
  server-timing/load.php
Labels: [Type] Bug, Infrastructure, Performance Lab Plugin

#790 Add early exit clauses to files with procedural code
  admin/load.php
  load.php
  modules/database/audit-autoloaded-options/helper.php
  modules/database/audit-autoloaded-options/hooks.php
  modules/images/dominant-color-images/helper.php
  modules/images/dominant-color-images/hooks.php
  modules/images/fetchpriority/can-load.php
  modules/images/fetchpriority/hooks.php
  modules/images/webp-support/helper.php
  modules/images/webp-support/hooks.php
  modules/images/webp-uploads/can-load.php
  modules/images/webp-uploads/helper.php
  modules/images/webp-uploads/hooks.php
  modules/images/webp-uploads/image-edit.php
  modules/images/webp-uploads/rest-api.php
  modules/images/webp-uploads/settings.php
  modules/js-and-css/audit-enqueued-assets/helper.php
  modules/js-and-css/audit-enqueued-assets/hooks.php
  server-timing/defaults.php
  server-timing/load.php
  server-timing/object-cache.copy.php
Labels: [Type] Enhancement, Infrastructure

#789 Fix incorrect function prefixes in Dominant Color Images
  modules/images/dominant-color-images/helper.php
  modules/images/dominant-color-images/hooks.php
  tests/modules/images/dominant-color-images/dominant-color-image-editor-gd-test.php
  tests/modules/images/dominant-color-images/dominant-color-image-editor-imageick-test.php
Labels: [Type] Enhancement, [Focus] Images, [Module] Dominant Color
