Repository WordPress/performance, pull requests merged in 2023-09, with the labels that each got.

#815 Add standalone plugin assets
  .gitattributes
  modules/images/dominant-color-images/.wordpress-org/banner-1544x500.png
  modules/images/dominant-color-images/.wordpress-org/banner-772x250.png
  modules/images/dominant-color-images/.wordpress-org/icon-128x128.png
  modules/images/dominant-color-images/.wordpress-org/icon-256x256.png
  modules/images/dominant-color-images/.wordpress-org/icon.svg
  modules/images/fetchpriority/.wordpress-org/banner-1544x500.png
  modules/images/fetchpriority/.wordpress-org/banner-772x250.png
  modules/images/fetchpriority/.wordpress-org/icon-128x128.png
  modules/images/fetchpriority/.wordpress-org/icon-256x256.png
  modules/images/fetchpriority/.wordpress-org/icon.svg
  modules/images/fetchpriority/readme.txt
  modules/images/webp-uploads/.wordpress-org/banner-1544x500.png
  modules/images/webp-uploads/.wordpress-org/banner-772x250.png
  modules/images/webp-uploads/.wordpress-org/icon-128x128.png
  modules/images/webp-uploads/.wordpress-org/icon-256x256.png
  modules/images/webp-uploads/.wordpress-org/icon.svg
  modules/images/webp-uploads/readme.txt
  plugins.json
Labels: [Type] Documentation, Infrastructure

#816 Remove PHPStan config file from plugin directory
  .gitattributes
Labels: [Type] Enhancement, Infrastructure

#831 Add an issue template for trac tickets
  .github/ISSUE_TEMPLATE/trac_ticket.md
Labels: Infrastructure, no milestone, [Type] Task

#837 Prepare 2.6.1 release
  load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#838 Merge 2.6.1 release back into `trunk`
  load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#841 Update `styfle /cancel-workflow-action` to 0.11.0 version
  .github/workflows/js-lint.yml
  .github/workflows/php-lint.yml
  .github/workflows/php-test-standalone-plugins.yml
  .github/workflows/php-test.yml
Labels: [Type] Bug, Infrastructure, no milestone

#842 Publish Dominant Color Images standalone plugin
  plugins.json
Labels: [Type] Documentation, Infrastructure
