Repository WordPress/performance, pull requests merged in 2023-01, with the labels that each got.

#619 Remove warning about multi-server environment from the SQLite module description
  admin/load.php
Labels: [Type] Bug, Needs Review, [Focus] Database, [Module] SQLite

#616 Enhance object-cache.php drop-in interoperability with other plugins
  load.php
  phpunit.xml.dist
  tests/load-tests.php
  tests/multisite.xml
  tests/utils/Filesystem/WP_Filesystem_MockFilesystem.php
Labels: [Type] Bug, Infrastructure

#623 Prepare 1.9.0
  load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#624 Merge 1.9.0 release back into `trunk`
  load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#629 Add `perflab_disable_object_cache_dropin` filter
  load.php
  tests/load-tests.php
Labels: [Type] Enhancement, [Focus] Measurement
