Repository WordPress/performance, pull requests merged in 2023-06, with the labels that each got.

#739 Implement migration prompt to migrate from SQLite module to standalone plugin due to removal in the following release
  admin/load.php
  modules/database/sqlite/admin.php
  modules/database/sqlite/can-load.php
  modules/database/sqlite/load.php
Labels: [Type] Enhancement, [Focus] Database, [Module] SQLite

#730 Add PHPStan and fix level 0 issues
  .github/workflows/php-lint.yml
  composer.json
  composer.lock
  load.php
  package.json
  phpstan.neon.dist
  tests/admin/load-tests.php
  tests/modules/images/dominant-color-images/dominant-color-test.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, Infrastructure

#729 Use static closures for minor performance improvement whenever instance access is not needed
  admin/load.php
  composer.json
  composer.lock
  load.php
  modules/database/sqlite/activate.php
  modules/database/sqlite/can-load.php
  modules/database/sqlite/deactivate.php
  modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-driver.php
  modules/images/webp-uploads/can-load.php
  modules/images/webp-uploads/image-edit.php
  modules/images/webp-uploads/load.php
  phpcs.xml.dist
  tests/bootstrap.php
  tests/load-tests.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/image-edit-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/modules/images/webp-uploads/rest-api-tests.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/server-timing/load-tests.php
  tests/server-timing/perflab-server-timing-tests.php
  tests/testdata/demo-modules/something/demo-module-2/activate.php
  tests/testdata/demo-modules/something/demo-module-2/deactivate.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, Infrastructure

#743 Fix SQLite module deactivation routine to make standalone plugin migration work correctly
  load.php
  modules/database/sqlite/deactivate.php
Labels: [Type] Bug, [Focus] Database, [Module] SQLite

#761 Update / PHP Stan Memory Limit
  composer.json
Labels: [Type] Enhancement, Infrastructure, no milestone

#762 Prepare 2.4.0 release
  admin/load.php
  load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone
