Repository WordPress/performance, pull requests merged in 2024-04, with the labels that each got.

#1103 Use plugin slug for generator tag
  load.php
  plugins/dominant-color-images/hooks.php
  plugins/dominant-color-images/readme.txt
  plugins/embed-optimizer/hooks.php
  plugins/embed-optimizer/readme.txt
  plugins/optimization-detective/helper.php
  plugins/optimization-detective/load.php
  plugins/optimization-detective/readme.txt
  plugins/speculation-rules/hooks.php
  plugins/webp-uploads/hooks.php
  plugins/webp-uploads/readme.txt
  tests/load-tests.php
  tests/plugins/dominant-color-images/dominant-color-test.php
  tests/plugins/embed-optimizer/embed-optimizer-test.php
  tests/plugins/optimization-detective/helper-tests.php
  tests/plugins/speculation-rules/speculation-rules-test.php
  tests/plugins/webp-uploads/load-tests.php
Labels: [Type] Enhancement, Infrastructure

#1106 Add crate-ci/typos config file with false positives.
  _typos.toml
Labels: [Type] Bug, Infrastructure, no milestone

#1105 Add auto-sizes generator tag.
  plugins/auto-sizes/hooks.php
  plugins/auto-sizes/readme.txt
  tests/plugins/auto-sizes/auto-sizes-test.php
Labels: [Type] Enhancement, [Focus] Images, [Plugin] Auto Sizes

#1108 Bump `@wordpress/env` from 8.13.0 to 9.6.0
  package-lock.json
  package.json
Labels: [Type] Enhancement, no milestone

#1112 Add support for autoloading enhancements in WordPress 6.6 trunk to autoloaded options Site Health check
  .github/typos.toml
  .github/workflows/spell-check.yml
  includes/site-health/audit-autoloaded-options/helper.php
  tests/includes/site-health/audit-autoloaded-options/audit-autoloaded-options-test.php
Labels: [Type] Enhancement, Infrastructure, Performance Lab Plugin

#1111 Implement support for annotating certain plugins as experimental
  includes/admin/load.php
  includes/admin/plugins.php
  load.php
Labels: [Type] Enhancement, Infrastructure, Creating standalone plugins

#1113 Merge `release/3.0.0` additions into `trunk` to unblock
  includes/admin/load.php
  includes/admin/plugins.php
  includes/site-health/audit-autoloaded-options/helper.php
  load.php
  tests/includes/site-health/audit-autoloaded-options/audit-autoloaded-options-test.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#1116 Delete option when uninstalling the Modern Image Formats plugin
  phpstan.neon.dist
  plugins/webp-uploads/readme.txt
  plugins/webp-uploads/uninstall.php
Labels: [Type] Enhancement, [Plugin] WebP Uploads, skip changelog

#1117 Update GitHub actions dependency
  .github/workflows/js-lint.yml
  .github/workflows/php-lint.yml
  .github/workflows/php-test-plugins.yml
  .github/workflows/php-test.yml
  .github/workflows/spell-check.yml
Labels: [Type] Enhancement, Infrastructure, no milestone, skip changelog

#981 Add codeql analysis workflow for JS
  .editorconfig
  .github/CODEOWNERS
  .github/workflows/codeql-analysis.yml
Labels: no milestone, [Type] Task, [Focus] Ecosystem Tools

#1119 Update `since` command for standalone plugin usage
  bin/plugin/cli.js
  bin/plugin/commands/since.js
Labels: [Type] Enhancement, Infrastructure, no milestone

#1084 Prevent detection script injection from breaking import maps in classic themes
  composer.json
  composer.lock
  plugins/optimization-detective/class-od-html-tag-processor.php
  plugins/optimization-detective/class-od-html-tag-walker.php
  plugins/optimization-detective/class-od-url-metric.php
  plugins/optimization-detective/detection.php
  plugins/optimization-detective/load.php
  plugins/optimization-detective/optimization.php
  plugins/optimization-detective/readme.txt
  tests/plugins/optimization-detective/class-od-html-tag-walker-tests.php
  tests/plugins/optimization-detective/optimization-tests.php
Labels: [Type] Bug, [Plugin] Optimization Detective

#1123 WPCS Improvement
  plugins/auto-sizes/hooks.php
  plugins/optimization-detective/optimization.php
Labels: [Type] Enhancement, no milestone, [Plugin] Optimization Detective, [Plugin] Auto Sizes, skip changelog

#1126 Fix passing error messages to wp_die() when plugin activation fails
  includes/admin/load.php
Labels: [Type] Bug, Performance Lab Plugin, skip changelog

#1127 Fix checking if plugin status is not install
  includes/admin/plugins.php
Labels: [Type] Bug, Performance Lab Plugin, skip changelog

#1128 Add missing uninstall.php to remove plugin's database option
  plugins/speculation-rules/load.php
  plugins/speculation-rules/readme.txt
  plugins/speculation-rules/uninstall.php
  tests/plugins/speculation-rules/speculation-rules-uninstall-tests.php
Labels: [Type] Enhancement, [Plugin] Speculation Rules

#1125 Prepare 3.0.0 release
  includes/admin/load.php
  includes/site-health/audit-autoloaded-options/helper.php
  includes/site-health/audit-autoloaded-options/hooks.php
  includes/site-health/load.php
  load.php
  plugins/optimization-detective/storage/data.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, skip changelog

#1134 Post 3.0.0 release merge
  composer.json
  composer.lock
  includes/admin/load.php
  includes/admin/plugins.php
  includes/site-health/audit-autoloaded-options/helper.php
  includes/site-health/audit-autoloaded-options/hooks.php
  includes/site-health/load.php
  load.php
  phpstan.neon.dist
  plugins/optimization-detective/class-od-html-tag-processor.php
  plugins/optimization-detective/class-od-html-tag-walker.php
  plugins/optimization-detective/class-od-url-metric.php
  plugins/optimization-detective/detection.php
  plugins/optimization-detective/load.php
  plugins/optimization-detective/optimization.php
  plugins/optimization-detective/readme.txt
  plugins/optimization-detective/storage/data.php
  plugins/speculation-rules/load.php
  plugins/speculation-rules/readme.txt
  plugins/speculation-rules/uninstall.php
  plugins/webp-uploads/readme.txt
  plugins/webp-uploads/uninstall.php
  readme.txt
  tests/plugins/optimization-detective/class-od-html-tag-walker-tests.php
  tests/plugins/optimization-detective/optimization-tests.php
  tests/plugins/speculation-rules/speculation-rules-uninstall-tests.php
Labels: [Type] Documentation, Infrastructure, no milestone, skip changelog

#1130 Bump minimum PHP requirement to 7.2
  .gitattributes
  .github/workflows/php-test-plugins.yml
  .github/workflows/php-test.yml
  .gitignore
  CONTRIBUTING.md
  bin/phpcs/phpcs.ruleset.xml
  build-cs/composer.json
  composer.json
  composer.lock
  load.php
  phpstan.neon.dist
  plugins/auto-sizes/auto-sizes.php
  plugins/auto-sizes/readme.txt
  plugins/dominant-color-images/load.php
  plugins/dominant-color-images/readme.txt
  plugins/embed-optimizer/load.php
  plugins/embed-optimizer/readme.txt
  plugins/optimization-detective/load.php
  plugins/optimization-detective/readme.txt
  plugins/speculation-rules/load.php
  plugins/speculation-rules/readme.txt
  plugins/webp-uploads/load.php
  plugins/webp-uploads/readme.txt
  readme.txt
Labels: [Type] Enhancement, Infrastructure, no milestone

#1145 Add settings link to Speculative Loading plugin action links
  phpstan.neon.dist
  plugins/speculation-rules/load.php
  plugins/speculation-rules/settings.php
  tests/plugins/speculation-rules/speculation-rules-settings-test.php
Labels: [Type] Enhancement

#1142 Exclude rel=nofollow links from prefetch/prerender
  plugins/speculation-rules/helper.php
  tests/plugins/speculation-rules/speculation-rules-helper-test.php
Labels: [Type] Bug, [Plugin] Speculation Rules

#1143 Exclude _wpnonce URLs in speculation rules
  plugins/speculation-rules/helper.php
  tests/plugins/speculation-rules/speculation-rules-helper-test.php
Labels: [Type] Bug, [Plugin] Speculation Rules

#1154 Release speculation-rules 1.2.1
  plugins/speculation-rules/load.php
  plugins/speculation-rules/readme.txt
  plugins/speculation-rules/settings.php
Labels: [Type] Documentation, [Plugin] Speculative Loading

#1160 Updated inline documentation
  plugins/webp-uploads/settings.php
Labels: [Type] Documentation

#1147 Do not show on the settings page and dismiss the pointer
  includes/admin/load.php
Labels: [Type] Bug, Performance Lab Plugin

#1155 Update readme with browser support and FAQ section about analytics and personalization
  plugins/speculation-rules/readme.txt
Labels: [Type] Documentation, [Plugin] Speculative Loading

#1162 Use PHP 7.2 features in Optimization Detective
  plugins/optimization-detective/class-od-html-tag-walker.php
  plugins/optimization-detective/class-od-url-metric.php
  plugins/optimization-detective/class-od-url-metrics-group-collection.php
  plugins/optimization-detective/class-od-url-metrics-group.php
  plugins/optimization-detective/helper.php
  plugins/optimization-detective/optimization.php
  plugins/optimization-detective/storage/class-od-storage-lock.php
  plugins/optimization-detective/storage/class-od-url-metrics-post-type.php
  plugins/optimization-detective/storage/data.php
  plugins/optimization-detective/storage/rest-api.php
Labels: [Type] Enhancement, [Plugin] Optimization Detective

#1148 Prevent showing warning notice about read-only file system when all plugins are installed and fix plugin links
  includes/admin/load.php
  includes/admin/plugins.php
Labels: [Type] Bug, Performance Lab Plugin, skip changelog

#1164 Fix composition of href exclude paths to account for JSON encoding and differing site/home URLs
  plugins/speculation-rules/helper.php
  tests/plugins/speculation-rules/speculation-rules-helper-test.php
Labels: [Type] Bug, [Plugin] Speculative Loading

#1166 Release Speculative Loading 1.2.2
  plugins/speculation-rules/load.php
  plugins/speculation-rules/readme.txt
Labels: [Type] Documentation

#1168 WPCS improvement
  includes/admin/plugins.php
Labels: [Type] Enhancement, Good First Issue, skip changelog

#1171 Remove plugins.json from PL plugin build
  .gitattributes
Labels: [Type] Bug, skip changelog

#1175 Avoid passing incomplete data to perflab_render_plugin_card() and show error when plugin directory API query fails
  includes/admin/load.php
  includes/admin/plugins.php
Labels: [Type] Bug, Performance Lab Plugin

#1177 Add support for AVIF image in site health
  includes/site-health/avif-support/helper.php
  includes/site-health/avif-support/hooks.php
  includes/site-health/load.php
Labels: [Type] Enhancement, Performance Lab Plugin

#1181 Add CODEOWNERS for AVIF Support site health check
  .github/CODEOWNERS
Labels: [Type] Enhancement, Infrastructure, no milestone, skip changelog

#1167 Prevent speculatively loading links to the uploads, content, plugins, template, or stylesheet directories
  plugins/speculation-rules/class-plsr-url-pattern-prefixer.php
  plugins/speculation-rules/helper.php
  tests/plugins/speculation-rules/speculation-rules-helper-test.php
Labels: [Type] Enhancement

#556 Add Web Worker Offloading module
  .eslintignore
  .github/CODEOWNERS
  .github/workflows/deploy-dotorg.yml
  .github/workflows/php-test-standalone-plugins.yml
  .github/workflows/php-test.yml
  .gitignore
  module-i18n.php
  modules/js-and-css/partytown-web-worker/can-load.php
  modules/js-and-css/partytown-web-worker/load.php
  package-lock.json
  package.json
  phpcs.xml.dist
  tests/modules/js-and-css/partytown-web-worker/partytown-web-worker-test.php
  webpack.config.js
Labels: [Type] Enhancement, [Focus] JS & CSS, no milestone, Needs Review

#1185 Facilitate embedding Optimization Detective in other plugins/themes
  plugins/optimization-detective/load.php
Labels: [Type] Enhancement, [Plugin] Optimization Detective
