Repository WordPress/performance, pull requests merged in 2024-01, with the labels that each got.

#916 Require Node v20
  .nvmrc
  package-lock.json
  package.json
Labels: [Type] Enhancement, Infrastructure, no milestone

#917 Revise migration pointer un-dismissal to work for all admins
  load.php
Labels: [Type] Enhancement, no milestone, Creating standalone plugins, [Focus] Standalone Plugins

#922 Prepare the auto-sizes module as a standalone plugin
  modules/images/auto-sizes/hooks.php
  modules/images/auto-sizes/load.php
  modules/images/auto-sizes/readme.txt
  tests/modules/images/auto-sizes/auto-sizes-test.php
Labels: [Focus] Images, no milestone, [Type] Task

#920 Load migration script in plugin setting page
  admin/js/perflab-module-migration-notice.js
  admin/js/perflab-plugin-management.js
  admin/load.php
Labels: [Type] Enhancement, Infrastructure, no milestone, Creating standalone plugins

#902 Merge `feature/creating-standalone-plugins` feature branch
  admin/js/perflab-module-migration-notice.js
  admin/js/perflab-plugin-management.js
  admin/load.php
  admin/plugins.php
  load.php
  tests/bootstrap.php
Labels: [Type] Enhancement, Infrastructure, no milestone

#923 Update `CODEOWNERS`, removing inactive contributors and adding newer active contributors
  .github/CODEOWNERS
Labels: [Type] Documentation, Infrastructure, no milestone, Performance Lab Plugin

#924 Update PHPCS formatting in tests
  phpcs.xml.dist
  tests/admin/load-tests.php
  tests/bootstrap.php
  tests/load-tests.php
  tests/modules/database/audit-autoloaded-options/audit-autoloaded-options-test.php
  tests/modules/images/dominant-color-images/dominant-color-test.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/modules/images/webp-uploads/rest-api-tests.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/server-timing/load-tests.php
  tests/server-timing/perflab-server-timing-tests.php
  tests/testdata/demo-modules/check-error/demo-module-4/can-load.php
  tests/testdata/demo-modules/something/demo-module-2/activate.php
  tests/testdata/demo-modules/something/demo-module-2/deactivate.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-audit-assets-transients-set.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-site-health-mock-responses.php
  tests/utils/Constraint/ImageHasSizeSource.php
  tests/utils/Constraint/ImageHasSource.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, Infrastructure

#931 PHPCS fixes
  tests/modules/images/auto-sizes/auto-sizes-test.php
Labels: [Focus] Images, no milestone, [Type] Task

#930 Fix JS linting
  .eslintrc.js
  admin/js/perflab-module-migration-notice.js
  admin/js/perflab-plugin-management.js
  modules/images/webp-uploads/fallback.js
  package.json
Labels: [Type] Bug, Infrastructure, no milestone

#927 Fix plugin deactivation link color
  admin/load.php
  admin/plugins.php
Labels: [Type] Bug, Infrastructure, no milestone, Creating standalone plugins, Performance Lab Plugin

#926 Prevent sending `Location` header during `test_perflab_aea_clean_aea_audit_action`
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-test.php
Labels: [Type] Bug, Infrastructure

#929 Merge trunk into feature/image-loading-optimization
  .eslintrc.js
  .github/CODEOWNERS
  .nvmrc
  .wordpress-org/blueprints/blueprint.json
  admin/js/perflab-module-migration-notice.js
  admin/js/perflab-plugin-management.js
  admin/load.php
  admin/plugins.php
  load.php
  modules/database/audit-autoloaded-options/can-load.php
  modules/images/webp-support/can-load.php
  modules/images/webp-uploads/fallback.js
  modules/js-and-css/audit-enqueued-assets/can-load.php
  package-lock.json
  package.json
  phpcs.xml.dist
  tests/admin/load-tests.php
  tests/bootstrap.php
  tests/load-tests.php
  tests/modules/database/audit-autoloaded-options/audit-autoloaded-options-test.php
  tests/modules/images/dominant-color-images/dominant-color-test.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/modules/images/webp-uploads/rest-api-tests.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/server-timing/load-tests.php
  tests/server-timing/perflab-server-timing-tests.php
  tests/testdata/demo-modules/check-error/demo-module-4/can-load.php
  tests/testdata/demo-modules/check-error/demo-module-4/load.php
  tests/testdata/demo-modules/something/demo-module-2/activate.php
  tests/testdata/demo-modules/something/demo-module-2/deactivate.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-audit-assets-transients-set.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-site-health-mock-responses.php
  tests/utils/Constraint/ImageHasSizeSource.php
  tests/utils/Constraint/ImageHasSource.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: Infrastructure, no milestone, [Type] Task, [Module] Image Loading Optimization

#932 Fix PHPStan errors in tests
  composer.lock
  tests/admin/load-tests.php
  tests/modules/images/webp-uploads/helper-tests.php
Labels: [Type] Bug, Infrastructure, no milestone

#898 Add PHPUnit tests for Image Loading Optimization
  composer.json
  composer.lock
  modules/images/image-loading-optimization/class-ilo-html-tag-processor.php
  modules/images/image-loading-optimization/detection.php
  modules/images/image-loading-optimization/optimization.php
  modules/images/image-loading-optimization/storage/data.php
  modules/images/image-loading-optimization/storage/post-type.php
  modules/images/image-loading-optimization/storage/rest-api.php
  tests/admin/load-tests.php
  tests/modules/images/image-loading-optimization/class-ilo-html-tag-processor-tests.php
  tests/modules/images/image-loading-optimization/detection-tests.php
  tests/modules/images/image-loading-optimization/hooks-tests.php
  tests/modules/images/image-loading-optimization/optimization-tests.php
  tests/modules/images/image-loading-optimization/storage/data-tests.php
  tests/modules/images/image-loading-optimization/storage/lock-tests.php
  tests/modules/images/image-loading-optimization/storage/post-type-tests.php
  tests/modules/images/image-loading-optimization/storage/rest-api-tests.php
  tests/modules/images/webp-uploads/helper-tests.php
Labels: [Type] Enhancement, [Focus] Images, no milestone, [Module] Image Loading Optimization

#936 Update feature branch with `trunk`
  .eslintrc.js
  .github/CODEOWNERS
  .nvmrc
  .wordpress-org/blueprints/blueprint.json
  admin/js/perflab-module-migration-notice.js
  admin/js/perflab-plugin-management.js
  admin/load.php
  admin/plugins.php
  composer.lock
  load.php
  modules/database/audit-autoloaded-options/can-load.php
  modules/images/webp-support/can-load.php
  modules/images/webp-uploads/fallback.js
  modules/js-and-css/audit-enqueued-assets/can-load.php
  package-lock.json
  package.json
  phpcs.xml.dist
  tests/admin/load-tests.php
  tests/bootstrap.php
  tests/load-tests.php
  tests/modules/database/audit-autoloaded-options/audit-autoloaded-options-test.php
  tests/modules/images/dominant-color-images/dominant-color-test.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/modules/images/webp-uploads/rest-api-tests.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/modules/js-and-css/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/server-timing/load-tests.php
  tests/server-timing/perflab-server-timing-tests.php
  tests/testdata/demo-modules/check-error/demo-module-4/can-load.php
  tests/testdata/demo-modules/check-error/demo-module-4/load.php
  tests/testdata/demo-modules/something/demo-module-2/activate.php
  tests/testdata/demo-modules/something/demo-module-2/deactivate.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-audit-assets-transients-set.php
  tests/testdata/modules/site-health/audit-enqueued-assets/class-site-health-mock-responses.php
  tests/utils/Constraint/ImageHasSizeSource.php
  tests/utils/Constraint/ImageHasSource.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, [Focus] JS & CSS, no milestone

#937 Fix new WPCS violation after trunk refresh
  tests/modules/js-and-css/speculation-rules/speculation-rules-helper-test.php
Labels: [Type] Bug, [Focus] JS & CSS, no milestone, Performance Lab Plugin, [Module] Speculation Rules

#941 Prepare 2.8.0 release
  admin/load.php
  admin/plugins.php
  load.php
  modules/database/audit-autoloaded-options/can-load.php
  modules/images/webp-support/can-load.php
  modules/js-and-css/audit-enqueued-assets/can-load.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, no milestone

#940 Removes outdated pieces of Speculation Rules logic that are no longer needed as of Chrome 121
  modules/js-and-css/speculation-rules/helper.php
  modules/js-and-css/speculation-rules/hooks.php
  tests/modules/js-and-css/speculation-rules/speculation-rules-helper-test.php
  tests/modules/js-and-css/speculation-rules/speculation-rules-test.php
Labels: [Type] Enhancement, [Focus] JS & CSS, no milestone, Performance Lab Plugin, [Module] Speculation Rules

#939 Add Speculation Rules settings and UI
  modules/js-and-css/speculation-rules/helper.php
  modules/js-and-css/speculation-rules/load.php
  modules/js-and-css/speculation-rules/settings.php
  tests/modules/js-and-css/speculation-rules/speculation-rules-helper-test.php
  tests/modules/js-and-css/speculation-rules/speculation-rules-settings-test.php
Labels: [Type] Enhancement, [Focus] JS & CSS, no milestone, Performance Lab Plugin, [Module] Speculation Rules

#945 Auto-sizes: Disallow direct file access
  modules/images/auto-sizes/load.php
Labels: [Focus] Images, no milestone, [Type] Task

#948 Introduce plugins folder for standalone plugins
  .gitattributes
  .github/workflows/deploy-standalone-plugins.yml
  bin/plugin/commands/build-plugins.js
  bin/plugin/commands/get-plugin-version.js
  bin/plugin/commands/test-plugins.js
  phpcs.xml.dist
  phpstan.neon.dist
  plugins.json
  plugins/.gitkeep
Labels: [Type] Enhancement, Infrastructure, no milestone

#914 Preload image for LCP element with background-image
  modules/images/image-loading-optimization/detection/detect.js
  modules/images/image-loading-optimization/optimization.php
  tests/modules/images/image-loading-optimization/optimization-tests.php
Labels: [Type] Enhancement, [Focus] Images, no milestone, [Module] Image Loading Optimization

#949 Include standalone plugin slugs in generator tag
  admin/plugins.php
  load.php
  tests/load-tests.php
Labels: [Type] Enhancement, Infrastructure, Performance Lab Plugin

#951 Escape path prefix and restrict it to be a pathname in Speculation Rules
  modules/js-and-css/speculation-rules/class-plsr-url-pattern-prefixer.php
  tests/modules/js-and-css/speculation-rules/plsr-url-pattern-prefixer-test.php
Labels: [Type] Bug, [Focus] JS & CSS, no milestone, [Module] Speculation Rules

#544 Run tests in different versions of PHP
  .github/workflows/php-test-standalone-plugins.yml
  .github/workflows/php-test.yml
  .gitignore
  .wp-env.json
  bin/plugin/commands/test-plugins.js
  build-cs/composer.json
  composer.json
  composer.lock
  package-lock.json
  package.json
  phpstan.neon.dist
  plugin-tests/.wp-env.json
  plugin-tests/multisite.xml
  plugin-tests/phpunit.xml
  tests/modules/images/dominant-color-images/dominant-color-image-editor-gd-test.php
  tests/modules/images/dominant-color-images/dominant-color-image-editor-imagick-test.php
  tests/modules/images/dominant-color-images/dominant-color-test.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/image-edit-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/multisite.xml
  tests/testdata/modules/images/dominant-color-images/video-play.svg
  tests/utils/TestCase/DominantColorTestCase.php
Labels: [Type] Enhancement, Infrastructure, no milestone, Needs Review

#957 Sanitize metric name for `Server-Timing` header
  server-timing/class-perflab-server-timing.php
  tests/server-timing/perflab-server-timing-tests.php
Labels: [Type] Bug, Infrastructure

#958 Add standalone plugin version constants for auto-sizes and speculation-rules
  load.php
Labels: [Type] Feature, Infrastructure

#953 Add Webpack config
  .github/workflows/deploy-dotorg.yml
  .github/workflows/deploy-standalone-plugins.yml
  .github/workflows/php-test-standalone-plugins.yml
  .github/workflows/php-test.yml
  .gitignore
  modules/images/image-loading-optimization/can-load.php
  modules/images/image-loading-optimization/detection.php
  modules/images/image-loading-optimization/detection/detect.js
  package-lock.json
  package.json
  phpcs.xml.dist
  webpack.config.js
Labels: [Type] Enhancement, [Focus] JS & CSS, no milestone, [Module] Image Loading Optimization

#959 Merge trunk into feature/modules-to-plugins
  .github/workflows/php-test-standalone-plugins.yml
  .github/workflows/php-test.yml
  .gitignore
  .wp-env.json
  admin/plugins.php
  bin/plugin/commands/test-plugins.js
  build-cs/composer.json
  composer.json
  composer.lock
  load.php
  package-lock.json
  package.json
  phpstan.neon.dist
  plugin-tests/.wp-env.json
  plugin-tests/multisite.xml
  plugin-tests/phpunit.xml
  server-timing/class-perflab-server-timing.php
  tests/load-tests.php
  tests/modules/images/dominant-color-images/dominant-color-image-editor-gd-test.php
  tests/modules/images/dominant-color-images/dominant-color-image-editor-imagick-test.php
  tests/modules/images/dominant-color-images/dominant-color-test.php
  tests/modules/images/webp-uploads/helper-tests.php
  tests/modules/images/webp-uploads/image-edit-tests.php
  tests/modules/images/webp-uploads/load-tests.php
  tests/multisite.xml
  tests/server-timing/perflab-server-timing-tests.php
  tests/testdata/modules/images/dominant-color-images/video-play.svg
  tests/utils/TestCase/DominantColorTestCase.php
Labels: [Type] Enhancement, Infrastructure, no milestone
