Repository WordPress/performance, pull requests merged in 2024-05, with the labels that each got.

#1196 Minor fix for `perflab_print_plugin_progress_indicator_script()`
  includes/admin/load.php
Labels: [Type] Enhancement, Performance Lab Plugin, skip changelog

#1191 Fix XPath indices to be 1-based instead of 0-based
  plugins/optimization-detective/class-od-html-tag-walker.php
  tests/plugins/optimization-detective/class-od-html-tag-walker-tests.php
  tests/plugins/optimization-detective/optimization-tests.php
Labels: [Type] Bug, [Plugin] Optimization Detective

#1184 Add plugin dependency support for activating performance features
  includes/admin/load.php
  includes/admin/plugins.php
Labels: [Type] Enhancement, Performance Lab Plugin

#1195 Fix PHPStan issues in Optimization Detective
  bin/phpstan/constants.php
  plugins/optimization-detective/class-od-url-metric.php
  tests/plugins/optimization-detective/class-od-html-tag-walker-tests.php
  tests/plugins/optimization-detective/class-od-url-metric-tests.php
  tests/plugins/optimization-detective/class-od-url-metrics-group-collection-tests.php
  tests/plugins/optimization-detective/class-od-url-metrics-group-tests.php
  tests/plugins/optimization-detective/detection-tests.php
  tests/plugins/optimization-detective/helper-tests.php
  tests/plugins/optimization-detective/hooks-tests.php
  tests/plugins/optimization-detective/optimization-tests.php
  tests/plugins/optimization-detective/storage/class-od-storage-lock-tests.php
  tests/plugins/optimization-detective/storage/class-od-url-metrics-post-type-tests.php
  tests/plugins/optimization-detective/storage/data-tests.php
  tests/plugins/optimization-detective/storage/rest-api-tests.php
  tests/plugins/optimization-detective/uninstall-tests.php
Labels: [Type] Bug, [Plugin] Optimization Detective

#1189 Ensure only HTML responses are optimized
  plugins/optimization-detective/optimization.php
  tests/plugins/optimization-detective/optimization-tests.php
Labels: [Type] Bug, [Plugin] Optimization Detective

#1194 Avoid _doing_it_wrong() for Server-Timing in Optimization Detective when output buffering is not enabled
  plugins/optimization-detective/optimization.php
Labels: [Type] Bug, [Plugin] Optimization Detective

#1188 Improve static analysis in Performance Lab plugin files
  bin/phpstan/constants.php
  composer.json
  composer.lock
  includes/admin/load.php
  includes/admin/plugins.php
  includes/admin/server-timing.php
  includes/server-timing/class-perflab-server-timing-metric.php
  includes/server-timing/class-perflab-server-timing.php
  includes/server-timing/defaults.php
  includes/server-timing/load.php
  includes/server-timing/object-cache.copy.php
  includes/site-health/audit-autoloaded-options/helper.php
  includes/site-health/audit-autoloaded-options/hooks.php
  includes/site-health/audit-enqueued-assets/helper.php
  includes/site-health/audit-enqueued-assets/hooks.php
  includes/site-health/avif-support/helper.php
  includes/site-health/avif-support/hooks.php
  includes/site-health/webp-support/helper.php
  includes/site-health/webp-support/hooks.php
  load.php
  phpstan.neon.dist
  tests/includes/server-timing/load-tests.php
  tests/includes/site-health/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/plugins/optimization-detective/optimization-tests.php
Labels: [Type] Enhancement, Performance Lab Plugin

#1198 Update PHPStan level to 1
  bin/phpstan/constants.php
  includes/admin/load.php
  includes/admin/server-timing.php
  phpstan.neon.dist
  plugins/dominant-color-images/hooks.php
  plugins/webp-uploads/helper.php
  plugins/webp-uploads/hooks.php
  plugins/webp-uploads/image-edit.php
  tests/includes/admin/load-tests.php
  tests/includes/admin/server-timing-tests.php
  tests/plugins/speculation-rules/speculation-rules-helper-test.php
Labels: [Type] Bug

#1199 Update PHPStan level to 2
  phpstan.neon.dist
  plugins/dominant-color-images/helper.php
  plugins/dominant-color-images/phpcs.xml.dist
Labels: [Type] Bug

#1192 Hide post embed iframes with visibility:hidden instead of clipping
  plugins/embed-optimizer/hooks.php
  tests/plugins/embed-optimizer/embed-optimizer-test.php
Labels: [Type] Bug, [Plugin] Embed Optimizer

#1200 Update PHPStan level to 3
  bin/phpstan/filtered-functions.stub
  phpstan.neon.dist
  plugins/webp-uploads/hooks.php
  tests/includes/admin/server-timing-tests.php
  tests/plugins/webp-uploads/rest-api-tests.php
Labels: [Type] Bug

#1201 Update PHPStan level to 4
  includes/server-timing/load.php
  phpstan.neon.dist
  plugins/webp-uploads/hooks.php
  plugins/webp-uploads/image-edit.php
  tests/includes/server-timing/load-tests.php
  tests/includes/server-timing/perflab-server-timing-tests.php
  tests/includes/site-health/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/plugins/webp-uploads/helper-tests.php
  tests/plugins/webp-uploads/image-edit-tests.php
Labels: [Type] Bug

#1204 Fix function stub docs
  bin/phpstan/filtered-functions.stub
Labels: [Type] Enhancement, no milestone

#1202 Update PHPStan level to 5
  phpstan.neon.dist
  tests/includes/server-timing/perflab-server-timing-tests.php
  tests/includes/site-health/audit-autoloaded-options/audit-autoloaded-options-test.php
  tests/includes/site-health/audit-enqueued-assets/audit-enqueued-assets-helper-test.php
  tests/includes/site-health/audit-enqueued-assets/audit-enqueued-assets-test.php
  tests/plugins/auto-sizes/auto-sizes-test.php
  tests/plugins/dominant-color-images/dominant-color-test.php
  tests/plugins/webp-uploads/load-tests.php
Labels: [Type] Bug

#1104 Avoid needless array allocation in rgb to hex conversion
  plugins/dominant-color-images/class-dominant-color-image-editor-gd.php
  plugins/dominant-color-images/helper.php
  tests/plugins/dominant-color-images/dominant-color-test.php
Labels: [Type] Enhancement, [Focus] Images, no milestone, [Plugin] Image Placeholders

#1210 Update PHPStan level to 8
  includes/server-timing/load.php
  phpstan.neon.dist
  plugins/optimization-detective/class-od-html-tag-walker.php
  plugins/webp-uploads/hooks.php
  plugins/webp-uploads/image-edit.php
  tests/plugins/optimization-detective/class-od-html-tag-walker-tests.php
  tests/plugins/optimization-detective/optimization-tests.php
Labels: [Type] Bug

#1179 Fix `WordPress.DB.DirectDatabaseQuery.DirectQuery` warning for Autoloaded Options Health Check
  includes/site-health/audit-autoloaded-options/helper.php
Labels: [Type] Bug, no milestone, [Module] Audit Autoloaded Options

#1216 Syntax highlight .stub files
  .gitattributes
Labels: [Type] Enhancement, Infrastructure, no milestone, skip changelog

#1213 Update PHPStan to 1.11.1
  composer.json
  composer.lock
  phpstan.neon.dist
  plugins/optimization-detective/storage/class-od-url-metrics-post-type.php
  plugins/optimization-detective/storage/rest-api.php
  tests/includes/server-timing/perflab-server-timing-tests.php
  tests/plugins/webp-uploads/helper-tests.php
  tests/plugins/webp-uploads/image-edit-tests.php
Labels: [Type] Enhancement

#1218 Use phpstan-assert to avoid ignoring errors
  plugins/optimization-detective/class-od-url-metric.php
  plugins/optimization-detective/storage/class-od-url-metrics-post-type.php
  plugins/optimization-detective/storage/rest-api.php
Labels: [Type] Enhancement, skip changelog

#1208 Updated code to display plugin settings link in the features screen and fix responsive layout for mobile
  includes/admin/load.php
  includes/admin/plugins.php
  tests/includes/admin/load-tests.php
Labels: [Type] Enhancement, Performance Lab Plugin

#1221 Bump plugin versions and add versions command to verify version consistency in plugins
  .github/workflows/deploy-standalone-plugins.yml
  bin/plugin/cli.js
  bin/plugin/commands/versions.js
  load.php
  package.json
  plugins/auto-sizes/auto-sizes.php
  plugins/auto-sizes/readme.txt
  plugins/dominant-color-images/load.php
  plugins/dominant-color-images/readme.txt
  plugins/embed-optimizer/load.php
  plugins/embed-optimizer/readme.txt
  plugins/optimization-detective/load.php
  plugins/optimization-detective/readme.txt
  plugins/speculation-rules/load.php
  plugins/speculation-rules/readme.txt
  plugins/webp-uploads/load.php
  plugins/webp-uploads/readme.txt
  readme.txt
Labels: [Type] Enhancement, skip changelog

#1223 Automatically detect version when running since command and allow updating all plugins at once
  bin/plugin/cli.js
  bin/plugin/commands/since.js
Labels: [Type] Enhancement, Infrastructure, no milestone, skip changelog

#1224 Improve readme command
  bin/plugin/cli.js
  bin/plugin/commands/changelog.js
  bin/plugin/commands/readme.js
  bin/plugin/commands/versions.js
Labels: [Type] Enhancement, no milestone, skip changelog

#1225 Publish 3.1.0 release
  includes/admin/load.php
  includes/admin/plugins.php
  includes/server-timing/hooks.php
  includes/server-timing/load.php
  includes/site-health/avif-support/helper.php
  includes/site-health/avif-support/hooks.php
  plugins/auto-sizes/readme.txt
  plugins/dominant-color-images/readme.txt
  plugins/embed-optimizer/readme.txt
  plugins/optimization-detective/optimization.php
  plugins/optimization-detective/readme.txt
  plugins/speculation-rules/readme.txt
  plugins/webp-uploads/deprecated.php
  plugins/webp-uploads/readme.txt
  plugins/webp-uploads/settings.php
  readme.txt
Labels: [Type] Documentation, skip changelog

#1230 Post 3.1.0 release merge
  includes/admin/load.php
  includes/admin/plugins.php
  includes/server-timing/hooks.php
  includes/server-timing/load.php
  includes/site-health/avif-support/helper.php
  includes/site-health/avif-support/hooks.php
  plugins/auto-sizes/readme.txt
  plugins/dominant-color-images/readme.txt
  plugins/embed-optimizer/readme.txt
  plugins/optimization-detective/optimization.php
  plugins/optimization-detective/readme.txt
  plugins/speculation-rules/readme.txt
  plugins/webp-uploads/deprecated.php
  plugins/webp-uploads/readme.txt
  plugins/webp-uploads/settings.php
  readme.txt
Labels: [Type] Documentation, Infrastructure, skip changelog

#1232 Check rel contains nofollow
  plugins/speculation-rules/helper.php
  plugins/speculation-rules/load.php
Labels: [Type] Bug, [Plugin] Speculative Loading

#1231 Re-remove unneeded phpcs:ignore
  plugins/dominant-color-images/class-dominant-color-image-editor-imagick.php
Labels: [Type] Bug, skip changelog

#1227 Add generate-pending-release-diffs command
  bin/generate-pending-release-diffs.sh
  package.json
Labels: [Type] Enhancement, no milestone, skip changelog

#1228 Add zip-plugin-builds command
  .github/CODEOWNERS
  bin/webpack/utils.js
  package.json
  webpack.config.js
Labels: [Type] Enhancement, no milestone, skip changelog

#1238 Harden autoloaded-options site health test for mis-implemented external object cache plugins
  plugins/performance-lab/includes/site-health/audit-autoloaded-options/helper.php
  tests/plugins/performance-lab/includes/site-health/audit-autoloaded-options/audit-autoloaded-options-test.php
Labels: [Type] Bug

#1172 Refactor optimization logic in Optimization Detective
  plugins/optimization-detective/class-od-html-tag-walker.php
  plugins/optimization-detective/class-od-preload-link-collection.php
  plugins/optimization-detective/class-od-url-metrics-group.php
  plugins/optimization-detective/load.php
  plugins/optimization-detective/optimization.php
  plugins/optimization-detective/readme.txt
  plugins/optimization-detective/storage/class-od-storage-lock.php
  plugins/optimization-detective/storage/class-od-url-metrics-post-type.php
  plugins/optimization-detective/storage/data.php
  plugins/optimization-detective/storage/rest-api.php
  tests/plugins/optimization-detective/class-od-html-tag-walker-tests.php
  tests/plugins/optimization-detective/class-od-url-metrics-group-tests.php
  tests/plugins/optimization-detective/optimization-tests.php
  tests/plugins/optimization-detective/storage/data-tests.php
Labels: [Type] Feature, [Plugin] Optimization Detective

#1246 Add consistent unit test naming
  tests/plugins/webp-uploads/helper-tests.php
  tests/plugins/webp-uploads/image-edit-tests.php
  tests/plugins/webp-uploads/load-tests.php
  tests/plugins/webp-uploads/rest-api-tests.php
Labels: [Type] Enhancement, skip changelog

#1257 Add Weston as code owner for Modern Image Formats plugin
  .github/CODEOWNERS
Labels: Infrastructure, no milestone, [Type] Task

#1176 Modern Image Formats: add AVIF output support
  plugins/webp-uploads/deprecated.php
  plugins/webp-uploads/fallback.js
  plugins/webp-uploads/helper.php
  plugins/webp-uploads/hooks.php
  plugins/webp-uploads/readme.txt
  plugins/webp-uploads/settings.php
  tests/plugins/webp-uploads/data/class-wp-image-doesnt-support-webp.php
  tests/plugins/webp-uploads/test-helper.php
  tests/plugins/webp-uploads/test-image-edit.php
  tests/plugins/webp-uploads/test-load.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Feature, [Plugin] Modern Image Formats

#1254 Fix linting of PHP files in tests/plugins
  composer.json
  tests/plugins/optimization-detective/test-optimization.php
Labels: [Type] Bug, skip changelog

#73 Add `picture` element support
  plugins/webp-uploads/helper.php
  plugins/webp-uploads/hooks.php
  plugins/webp-uploads/load.php
  plugins/webp-uploads/picture-element.php
  plugins/webp-uploads/settings.php
  tests/plugins/webp-uploads/test-helper.php
  tests/plugins/webp-uploads/test-load.php
  tests/plugins/webp-uploads/test-picture-element.php
  tests/plugins/webp-uploads/test-settings.php
  tests/utils/TestCase/ImagesTestCase.php
Labels: [Type] Enhancement, [Focus] Images, [Module] Picture Element

#1260 Fix Server-Timing compatibility with other plugins that do output buffering
  plugins/performance-lab/includes/server-timing/class-perflab-server-timing.php
  plugins/performance-lab/includes/server-timing/load.php
  tests/plugins/performance-lab/includes/server-timing/test-load.php
Labels: [Type] Bug, Performance Lab Plugin

#1264 Fix lint-staged config for plugins
  lint-staged.config.js
  package-lock.json
  package.json
Labels: [Type] Enhancement, skip changelog

#1266 Prevent lint-staged from linting unstaged plugin files
  lint-staged.config.js
Labels: [Type] Bug, skip changelog
